projects/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('proj.urls', namespace='proj')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

projects/myproject/proj/urls.py
from django.urls import path
from . import views
from .views import render_pdf_view,CustomerListView,customer_render_pdf_view








app_name='proj'

urlpatterns=[
    path('',CustomerListView.as_view(), name='customer-list-view'),
    path('test/',render_pdf_view, name='test-view'),
    path('pdf/<pk>',customer_render_pdf_view, name='customer-pdf-view'),
    path ("counter", views.counter, name = "counter"),
    path('register',views.register, name="register"),
    path('login',views.login, name="login"),
    path('logout',views.logout, name="logout"),
    path("",views.sidebar, name="sidebar"),
   
    
    
]

projects/myproject/proj/models.py
from django.db import models

# Create your models here.
class Feature(models.Model):
    name = models.CharField(max_length=100)
    details = models.CharField(max_length=500)
    featured= models.BooleanField(null=True, default=True)

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField()
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)    

projects/myproject/proj/views.py
from ast import Not
from .models import Feature
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth.hashers import make_password,check_password

from cmath import pi
from msilib.schema import ListView
from urllib import response
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from .models import Customer



# Create your views here.
def sidebar(request):
    features = Feature.objects.all()
    return render(request,'sidebar.html',{'features':features})

   
def register(request):
    if request.method =='POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']

        username = request.POST['username']
        email = request.POST['email']
        encryptedpassword = make_password(request.POST['password'])
        encryptedpassword = make_password(request.POST['password'])
        

        if encryptedpassword == encryptedpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username already exists')
                return redirect('register')
           
            elif User.objects.filter(email=email).exists():
                messages.info(request,'email already exists') 
                return redirect('register')
            elif User.objects.filter(last_name=last_name).exists():
                messages.info(request,'lastname already exists') 
                return redirect('register')
            elif User.objects.filter(first_name=first_name).exists():
                messages.info(request,'firstname already exists') 
                return redirect('register')        
            else:
                user = User.objects.create_user(username=username, email=email, password=encryptedpassword,last_name=last_name,first_name=first_name ) 
                user.save();
                return redirect('login')  
        else:
            messages.info(request,'passwords not the same') 
            return redirect('register') 
    else:
        return render(request,'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        encryptedpassword = make_password(request.POST['password'])

        user = auth.authenticate(username=username, encryptedpassword=encryptedpassword)

        if user is not None:
            auth.login(request, user)
            return redirect('/')

        else:
            messages.info(request,'Credentials invalid')
            return redirect('login')    

    else:
        return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')        
    

def counter(request):
    text = request.POST["text"]
    amount_of_words=len(text.split())
    return HttpResponse(request,'counter.html', { "amount":amount_of_words})

# Create your views here.
class CustomerListView(ListView):
    model = Customer
    template_name = 'customers/stamp.html'

def customer_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    customer = get_object_or_404(Customer,pk=pk)

    template_path = 'customers/pdf2.html'
    context={'customer':customer}

    #Create a django response object and specify content_type as pdf
    response = HttpResponse(content_type = 'application/pdf')
    # response['Content-Disposition'] = 'attachment; filename = "report.pdf"'
    
    #find the template and render it
    template = get_template(template_path)
    html = template.render(context)

    #create pdf
    pisa_status = pisa.CreatePDF(
        html, dest = response
    )

    #if error then show some funny view
    if pisa_status.err:
        return HttpResponse("we had some errors<pre>" + html + "<pre>")
    return response    






def render_pdf_view(request):
    template_path = 'customers/pdf1.html'
    context={'myvar':'this is my template path'}

    #Create a django response object and specify content_type as pdf
    response = HttpResponse(content_type = 'application/pdf')
    # response['Content-Disposition'] = 'attachment; filename = "report.pdf"'
    
    #find the template and render it
    template = get_template(template_path)
    html = template.render(context)

    #create pdf
    pisa_status = pisa.CreatePDF(
        html, dest = response
    )

    #if error then show some funny view
    if pisa_status.err:
        return HttpResponse("we had some errors<pre>" + html + "<pre>")
    return response    

projects/myproject/templates/TRIAL1.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>LOGIN FORM</title>
    <link rel="stylesheet" href="Login.css">
  </head>
  <body>
    <form class="FORM" >
      <h1>Login</h1>

      <div class="textboxdiv">
        <input type="text" placeholder="username" value="Username" required/>
      </div>
      <div class="textboxdiv">
        <input type="password" placeholder="password" value="passwd" required/>
      </div>
      <input type="submit" placeholder="Login" class="Loginbtn">
      <div class="signup">
        I don't have an account?
        </br>
        <a href="#">Sign up</a>
      </div>
    </form>
  </body>
</html>

projects/myproject/templates/button.html
<html>
    <head>
        <title>button</title>
        <style>
            #image{
                display: none;
            }
        </style>
    </head>
    <body>
        <div>
            <h1>This is the button</h1>
            <img id="image" src="templates/010.jpg" alt=" JPG image">
        </div>
        <button type="button" onclick="show()" id="btn">Show image</button>
        <script>
            function show(){
                document.getElementById("image").style.display = "block";
                document.getElementById("btn").style.display="none";
            }
        </script>
        
    </body>
</html>

projects/myproject/templates/customers/pdf1.html
<html>
    <head>
        <meta charset="utf-8">
        <title>pdf test</title>
    </head>
    <body>
        {{myvar}}
    </body>
</html>

projects/myproject/templates/customers/pdf2.html
<html>
    <head>
        <meta charset="utf-8">
        <title>pdf test</title>
        <style>
            table,th,td{
                border:1px solid black;
            }
            .centre{
                text-align: center;

            }
            .image1{
                margin-left: 650px;
            }
            .image{
                margin-left: 300px;
            }
            .detail{
                margin-left: 100px;
            }
            .id{
                margin-left: 400px;
            }
            .off{
                margin-left: 70px;
            }
            
        </style>
    </head>
    <body>
        {% block content %}
        
        <div class="">
            <h1>IMAGE1</h1><h1 class="image1">IMAGE2</h1>
                <h1 class="centre">MOI UNIVERSITY 
                    <p>EXAMINATION CARD</p>
                    <p>2019/2020 ACADEMIC YEAR</p>
                </h1>
            
            <p></p>
            
            <div class="detail">
                <h2>Office of the Deputy Vice Chancellor (Academic Affairs)</h2>
                <p>AUTHORIZATION TO SIT UNIVERSITY EXAMINATION</p>
                <h1>TED/90/18</h1>
                <h1>MWATSUKIZI SWALEH</h1>
                <p>Bachelor of Education (Technology Education And Computer)</p>
                <p>STAGE: Y4S1 SEMESTER: SEM1 21/22</p>
            </div>
            <p class="id">##73865**</p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">CODE</th>
                        <th scope="col">DESCRIPTION</th>
                        <th scope="col">BOOKLET NO</th>
                        <th scope="col">LECTURER SIGNATURE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">
                            <P>BCT 411E</P>
                            <P>BCT 421E</P>
                            <P>BCT 431E</P>
                           <P>EDU 499</P>
                           <P>EMP 410</P>
                           <P>EMP 411</P>
                           <P>TEC 400</P>
                           <P>TEC 401</P>
                           <P>TEC 490</P>
                        </th>
                        <td>
                            <P>Architectural Drawing</P>
                            <p>Structures II</p>
                            <P>Quantity Survey II</P>
                            <p>Research Project</p>
                            <p>Environmental Education</p>
                            <p>Educational Administration & Management</p>
                            <p>Technology Trip II(Week 1)</p>
                            <p>Micro Processing System</p>
                            <p>Project (Final Year)</p>

                        </td>
                       
                    </tr>
                    
                </tbody>
                

            </table>
        
            <div class="off">
            <h1>Official Signature $ Stamp:</h1>
            <p><h1>73865</h1></p>
            </div>
            
            <div class="image">
                <img src="{{customer.logo.path}}" height="200px"/>
    
            </div>
            


        </div>
        {% endblock %}


       





       
         
    </body>
</html>

projects/myproject/templates/customers/stamp.html
<html>
<head>
    <meta charset="UTF-8"/>
    <Meta name="viewport" content="width=device.width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <style>
        button{
    border-radius: 10px;
    font-size: 40px;
    padding: 10px;
    margin: 20px;
    cursor: pointer;
    width: 150px;
    background: white;
    color: black;
    border: none;
    outline: none;
    position:static;
    top: 0;
    font-size: 30px;
    border-radius: 5px;
    cursor: pointer;

}
.container{
    text-align: center;
    flex-direction: column;

}
#click{

    margin-top:150px;
    margin-right:100px;

}
#click1{
    margin-top:150px;
    margin-right:100px;
    margin-top: 20px;

}



@import url("https://fonts.googleapis.com/css?family=Poppins");
*{
    margin: 0;
    padding: 0;
    font-family: "Poppins", sans-serif;
}
html{
    height: 100%;

}
.zero{
    width: 100%;
    height: 80px;
    text-align: center;
    padding: 10px;
    color: white;
    background-color: black;
    margin: 0;
    
}

.one{
    padding: 10px;
    width: 100%;
    height: 80px;
    background-color:green;
    margin:0;
    text-align: center;
    color: white;
   
}
.one1{
    width: 20%;
    height:70px;
    background-color:white;
    margin: 10px;
    border-radius: 20px;
    margin-right: 10px;
    margin-left: auto;
    shape-outside:circle(10);

}
.two{
    text-align: center;
    padding: 10px;
    width: 60%;
    height: 40px;
    background-color:lightgreen;
    margin-top: 10px;
    margin-left: 200px;
    position: static;
    
}
.moving{
    color:red;
    font-size: 20px;
}
.three,.four,.five{
    text-align: center;
    padding: 10px;
    width: 30%;
    height: 180px;
    background-color:rgb(21, 255, 0);
    margin-top: 20px;
    margin-left: 400px;
    position: static;
}
.six{
    text-align: center;
    padding: 10px;
    width: 60%;
    height: 40px;
    background-color:lightgreen;
    color: white;
    margin-top: 10px;
    margin-left: 200px;
    position: static;
}
.seven{
    text-align: center;
    padding: 10px;
    width: 100%;
    height: 80px;
    background-color:blue;
    margin-top: 10px;
    position: static;
}
.stamp{
    text-align: center;
    font-size: 30px;
    color: red;
    margin-top: 200px;
}
.group{
    margin: 10px 0px 10px 0px;
}
.top{
    width: 100%;
    height: 80px;
    
}
body{
    background: #03a9f4;
    height: 100%;
    position: relative;

}
.sidebar{
    background: #ffffff;
    height: 100%;
    width: 0px;
    position: absolute;
    top: 0;
    font-size: 35px;
    font-weight: 700px;
    overflow:hidden; 
    transition: 0.25s ease-in-out;

}
.content{
    margin-top: 80px;
    
    

}
.option{
    width: 100%;
    height: 50px;
    margin: 20px 0;
    padding: 20px;
    cursor: pointer;
    


}
.option:hover{
    background: #23a811;
}
.btn1{
    display: block;
    background: white;
    color: #03a9f4;
    width: 50px;
    height: 50px;
    border: none;
    outline: none;
    margin-left: 40px;
    margin-right: auto;
    margin-top: 10px;
    position: fixed;
    top: 0;
    font-size: 30px;
    border-radius: 5px;
    cursor: pointer;


}
    </style>
    <title>Stamp exam card</title>
</head>
<body>

  <div class="top">
      <h1 class="zero">STUDENT PORTAL</h1>
      <div class="stamp">
        
          <p id="butt"></p>
          <div class="container"><button id="click">STAMP</button></div>
          <div class="container">
            {% block content %}
            {% for customer in object_list %}
            {{customer}}
           
                
            <a href="{% url 'proj:customer-pdf-view' customer.pk%}"><button class="btn btn-primary">Download</button></a>

  
            {% endfor %}
            {% endblock content %}
            
           
          </div>
          

      </div>
     
        <div class="sidebar" id="sidebar">
            <div class="content">
                <div class="option">Home</div>
                <div class="option">About</div>
                <div class="option">Help</div>
                <div class="option">Feedback</div>
                <div class="option">Settings</div>

            </div>
        </div>
  </div> 

   
  
    <button class="btn1" onclick="toggle()"><i class="fas fa-bars"></i></button>
    <script>
        var toggled = true;
        function toggle(){
            if(toggled==false){
                document.getElementById("sidebar").style.width="0";
                toggled = true;
            }else if(toggled==true){
                document.getElementById("sidebar").style.width="300px";
                toggled = false;
            }
        }

        let User={
            name:"{{user.username}}",
            

        };
        function stamp(){
            document.getElementById("butt").innerHTML= "Congratulations " +User.name+ ", you have successifully stamped your exam card you can now download it";
        }
        User.message=stamp;
        document.getElementById("click").onclick=User.message;
    </script>

</body>

</html>

projects/myproject/templates/image.html
<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1>This is the document</h1>
        <script>

            var doc = new jsPDF();
            var imageData = 'data:image/jpg;base64';Base64.encode('010.jpg');
            doc.setFontSize(40);
            doc.text(20,30,'Hello world');
            doc.addImage(imageData,'jpg',15,40,180,160);
            doc.save("output.pdf");


        </script>
    </body>
</html>

projects/myproject/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Add icon library -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>MOI UNIVERSITY</title>
    <style>
      body{
  background-color: grey;
}
.SHAPE{
  position: absolute;
  font-size: 20px;
  background-color: green;
  width: 400px;
  height: 570px;
  padding-left: 50px;
  margin-left: 450px;
  margin-right: 600px;
  border-radius: 30px;
  align-items: center;
}
h3{
  border-color: yellow;
  margin-right: 10px;
  margin-left: 70px;
  margin-top: 150px;

}
.font{
  font-size: 15px;
}
h5{
  margin-left: 70px;
}
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;


}

.icon {
  padding: 10px;
  background: brown;
  color: white;
  min-width: 50px;
  text-align: center;
  border-radius:5px 0  0  5px;

}

.input-field {
  width: 70%;
  padding: 10px;
  outline: none;
  border-radius:0  5px 5px  0;
}

/*.input-field:focus {
  border: 2px solid dodgerblue;
}*/

/* Set a style for the submit button */
.btn {
  background-color: brown;
  color: white;
  padding: 10px 15px;
  border: none;
  cursor: pointer;
  width: 60%;
  opacity: 0.9;
  margin-left: 50px;
  margin-top: 10px;
}
.h4{
  margin-top: 15px;
  font-size: 15px;
  margin-left: 20px;
  

}

.Forgot{
  margin-bottom: 100px;
  margin-left: 40px;
  padding-bottom: 50px;
  color: white;
  font-style:oblique;
  
}

.btn:hover {
  opacity: 1;
}
.foot{

  height: 40px;
  width: 100%;
  background-color: black;
  margin-top:600px;
  position: absolute;
  
}
.graph{
  text-align: center;
  color: white;

}
h1{
  color: red;
}

    </style>

    <script type="text/javascript">
    function validate() {
      if (document.myform.Regno.value=="") {
        alert("please enter your registration number");
        document.myform.Regno.focus()
        return false

      }

      else if (document.myform.email.value=="") {
        alert("please enter the email address");
        document.myform.email.focus()
        return false

      }else if (document.myform.password.value=="") {
        alert("please enter your password");
        document.myform.password.focus()
        return false

      }
      else {
        return true
      }
    }

    </script>

  </head>
  <body>
    <div class="SHAPE">
      {% for message in messages %}
      <h1>{{message}}</h1>
      {% endfor %}

      <form method="POST" action="login" style="max-width:500px;margin:auto" name="myform" onsubmit="return(validate());">
        {% csrf_token %}
        <h3>MOI UNIVERSITY</h3>
      <h5>Foundation of knowledge</h5>
      <div class="input-container">
        <i class="fa fa-user icon"></i>
        <input class="input-field" type="text" placeholder="username" id="text" name="username">
      </div>

      <div class="input-container">
        <i class="fa fa-key icon"></i>
        <input class="input-field" type="password" placeholder="password" id="word" name="password">
      </div>
      <div>
        <input type="checkbox">
        <label class="font">Remember me</label><br>
      </div>
      <button type="submit" class="btn">Log In</button>
      <div class="Forgot">
        <h4 class="h4">Forgot your password?</h4>
      </div>
      


    </form>

    </div>
    <footer class="footer">
      <div class="foot">
        <p class="graph">Copyright &copy; your website 2022</p>
      </div>
    </footer>
   

  </body>
 
</html>

projects/myproject/templates/navibar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>navibar</title>
    
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      *{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body{
  background: url(010.jpg);
  background-size: cover;
  font-family: sans-serif;
  background-position: center ;
  
}

.moving{
  color: blue;
  font-size: 30px;
  text-shadow: 6px 6px 6px black;
  
}
.menubar{
   background: rgb(0,100,0);
   text-align: center;
}
.menubar ul{
  display: inline-flex;
  list-style:none;
  color: #fff;
}
.menubar ul li{
  width: 120px;
  padding: 15px;
  margin: 15px;
  
} 
.menubar ul li a
{
  text-decoration: none;
  color:#fff;
}
.active, .menubar ul li:hover{
  background:#2bab0d;
  border-radius: 3px;
}
.menubar .fa{
  margin-right: 8px;
}
.submenu{
  display: none;
}
.menubar ul li:hover .submenu{
  display: block;
  position: absolute;
  background: rgb(0,100,0);
  margin-top: 15px;
  margin-left: -15px;
}
.menubar ul li:hover .submenu ul{
  display: block;
  margin: 10px;
}
.menubar ul li:hover .submenu ul li{
  width: 150px;
  padding: 10px;
  border-bottom: 1px dotted #fff;
  background: transparent;
  border-radius: 0;
  text-align: left;
}
.menubar ul li:hover .submenu ul li a{
  color: #b2ff00;

}
.fa-angle-right{
  float: right;
}
.submenu-1{
  display: none;
}
.hover-me:hover .submenu-1{
  position: absolute;
  display: block;
  margin-top: -40px;
  margin-left: 140px;
  background: rgba(0,100,0);
}
    </style> 
  </head>
  <body>
    <div class="menubar">
    <ul>
      <li class="active"><a href="#"><i class="fa fa-home" ></i>Home</a></li>
      <li><a href="#"><i class="fa fa-user" ></i>About us</a>
          <div class="submenu">
            <ul>
              <li><a href="#">Team</a></li>
              <li><a href="#">Clients</a></li>
              <li class="hover-me"><a href="#">Career<i class="fa fa-angle-right"></i></a>
                <div class="submenu-1">
                  <ul>
                    <li><a href="#">Education</a></li>
                    <li><a href="#">Computer science</a></li>
                    <li><a href="#">Engineering</a></li>
                    <li><a href="#">Medicine</a></li>
      
                  </ul>
                </div>
              </li>
              <li><a href="#">Legacy</a></li>

            </ul>
          </div>


      </li>
      <li><a href="#"><i class="fa fa-phone" ></i>Contact</a>
        <div class="submenu">
            <ul>
              <li><a href="#">Email</a></li>
              <li><a href="#">Phone</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Twitter</a></li>

            </ul>
        </div> 

      </li>
      <li><a href="#"><i class="fa fa-users" ></i>Clients</a></li>
      <li><a href="#"><i class="fa fa-clone" ></i>Services</a></li>
      <li><a href="#"><i class="fa fa-angellist" ></i>investors</a></li>
      <li><a href="#"><i class="fa fa-clone" ></i>News</a></li>
      
    </ul>
</div>

  <marquee class="moving">WELCOME TO MOI UNIVERSITY,THE UNIVERSITY WITH A DIFFERENCE</marquee>


  </body>
</html>

projects/myproject/templates/night.html
<html>
<head>
    <title>day/night checkbox</title>
    <link rel="stylesheet" href="style2.css">
</head>
<body>
 <label >
     <input type="checkbox">
     <span class="check"></span>
 </label>
     
</body>
</html>

projects/myproject/templates/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User registration form</title>
    <style>
body{
  font-size: 12px;
  background-color:gray;
  width: 100%;
}



.header{
  padding: 20px;
  margin:50px auto 0px;
  width: 30%;
  background:blue ;
  color: white;
  text-align: center;
  border-bottom: none;
  border-radius: 10px 10px 0px 0px;
  border: 1px solid #80C4DE;





}
.group{
  margin: 10px 0px 10px 0px;

}
.group input{
  width: 93%;
  height:20px;
  padding: 5px 10px;
  font-size: 16px;
  border-radius: 5px;
  border:1px solid gray;
}
.group label{
  display: block;
  text-align: left;
  margin: 3px;

}
.check{
  margin-top: 10px;
  
}

form{
  width: 30%;
  margin: 0px auto;
  padding: 20px;
  border: 1px solid #80C4DE;
  background: rgb(151, 68, 68);
  border-radius: 0px 0px 10px 10px;
  position:relative;

}
#welcome{
  color: white;
}
.radio{
  display:block;
}
h1{
  color:red;
  text-align: center;

}
    </style>
  </head>
  <body>
    {% for message in messages %}
    <h1>{{message}}</h1>
    {% endfor %}
    <div class="header">
      <h2>Register</h2>
    </div>
    <form action="register" method="POST">
      {% csrf_token %}
      <div class="group">
        <label >Username</label>
        <input type="text" name="username" placeholder="Please enter your firstname" required>

      </div>
      <div class="group">
        <label >Firstname</label>
        <input type="text" name="first_name" placeholder="Please enter your firstname" required>

      </div>
      
      <div class="group">
        <label >Lastname</label>
        <input type="text" name="last_name" placeholder="Please enter your lastname" required>

      </div>
      <div>
        <label for="Male">Male</label>
        <input type="radio" name="gender" class="check" required><br><br>
        
      </div>
      <div>
        <label for="female">Female</label>
        <input type="radio" name="gender" required><br><br>
      </div>
      
      <div class="group">
        <label >Email</label>
        <input type="text" placeholder="Please enter your email-address" name="email" required>

      </div>
      <div class="group">
        <label>Password</label>
        <input type="password" placeholder="Please enter your Password" name="password" required>
      </div>
      <div class="group">
        <label >confirm Password</label>
        <input type="password" placeholder="Confirm your password" name="password" required>
      </div>
      <div class="group">
        <button type="submit" name="register" class="btn">Register</button>
      </div>
      <a href="index.html">sign in</a>

    </form>

  </body>
</html>